format = "$directory$character"
add_newline = false
right_format = "$all"

palette = "one_dark_two"


[aws]
symbol = "  "

[bun]
symbol = " "
format = '[$symbol($version )]($style)'

[conda]
symbol = " "
format = '[$symbol($environment )]($style) '

[directory]
read_only = " 󰌾"
truncation_length = 3

[docker_context]
symbol = " "
format = '[$symbol ]($style)'

[elixir]
symbol = " "
format = '[$symbol($version )]($style)'

[git_branch]
symbol = " "

[golang]
symbol = " "
format = '[$symbol($version )]($style)'

[hostname]
ssh_symbol = " "
format = '[($hostname )$ssh_symbol]($style)'
style = 'bold dimmed blue'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "
format = '[$symbol($version )]($style)'

[nodejs]
symbol = " "
format = '[$symbol($version )]($style)'

[package]
symbol = "󰏗 "
format = '[$symbol($version )]($style)'

[python]
symbol = " "
format = '[$symbol($version )(\($virtualenv\) )]($style)'

[rust]
symbol = " "
format = '[$symbol($version )]($style)'

[username]
format = '[$user]($style)@'
style_root = 'bold dimmed red'
style_user = 'bold dimmed yellow'

[palettes.one_dark_two]
magenta   = "#C88BDA"
red       = "#E27881"
orange    = "#E79C7E"
yellow    = "#EAC786"
green     = "#98C379"
cyan      = "#62BAC6"
blue      = "#71B9F4"
text      = "#E6E6E6"
subtext1  = "#C9CCD3"
subtext0  = "#ABB2BF"
overlay2  = "#969DAB"
overlay1  = "#818896"
overlay0  = "#6C7280"
surface2  = "#5B626D"
surface1  = "#4A505A"
surface0  = "#393E47"
base      = "#282C34"
mantle    = "#21252B"
crust     = "#1D1F23"
